In [1]:
import torch

def feats2clip(feats, stride, clip_length, padding = "replicate_last", off=0):
    if padding =="zeropad":
        print("beforepadding", feats.shape)
        pad = feats.shape[0] - int(feats.shape[0]/stride)*stride
        print("pad need to be", clip_length-pad)
        m = torch.nn.ZeroPad2d((0, 0, clip_length-pad, 0))
        feats = m(feats)
        print("afterpadding", feats.shape)
        # nn.ZeroPad2d(2)

    idx = torch.arange(start=0, end=feats.shape[0]-1, step=stride)
    idxs = []
    for i in torch.arange(-off, clip_length-off):
        idxs.append(idx+i)
    
    idx = torch.stack(idxs, dim=1)
    
    
    if padding=="replicate_last":
        idx = idx.clamp(0, feats.shape[0]-1)
    print(idx)
    return feats[idx,...]

feats = torch.randn(900, 512)
clipped_feats = feats2clip(feats, stride=30, clip_length=30)
print(clipped_feats.shape)

tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
          44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
          58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
          74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
          88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
         104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
         118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
         134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
         164, 165, 166, 167, 16

In [7]:
from SoccerNet.Downloader import getListGames
from SoccerNet.Downloader import SoccerNetDownloader
from SoccerNet.Evaluation.utils import getMetaDataTask
from pprint import pprint
labels, num_classes, dict_event, inv_dict = getMetaDataTask("caption", "SoccerNet", 2)
import inspect

# 関数の引数を取得する
signature = inspect.signature(getListGames)
parameters = signature.parameters

for param in parameters.values():
    print(f"Name: {param.name}, Default: {param.default}, Kind: {param.kind}")
listGames = getListGames('test', task="caption")
print(num_classes)

Name: split, Default: v1, Kind: POSITIONAL_OR_KEYWORD
Name: task, Default: spotting, Kind: POSITIONAL_OR_KEYWORD
Name: dataset, Default: SoccerNet, Kind: POSITIONAL_OR_KEYWORD


In [10]:
import numpy as np
label = 0
frame = 10
window_size_frame = 3
event = 'corner'
label_half1 = np.zeros((20, num_classes+1))

label_half1[:,0]=1 # those are BG classes
print(label_half1)
label_half1[frame//window_size_frame][0] = 0 # not BG anymore

label_half1[frame//window_size_frame][label+1] = list(dict_event.keys()).index(event) + 1 # 0 is for no action
print(label_half1)
for i in dict_event:
    print(list(dict_event.keys()).index(event)+1)


[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
1
1
1
1
1
1
1
1
1
1
1
1
1


In [37]:
from pprint import pprint
print(labels)
pprint(num_classes)
pprint(dict_event)
pprint(inv_dict)

Labels-caption.json
1
{'': 0,
 'comments': 0,
 'corner': 0,
 'injury': 0,
 'penalty': 0,
 'penalty-missed': 0,
 'r-card': 0,
 'soccer-ball': 0,
 'soccer-ball-own': 0,
 'substitution': 0,
 'whistle': 0,
 'y-card': 0,
 'yr-card': 0}
{0: 'comments'}
